Make bootstrap script more stable

diff --git a/.bin/bootstrap b/.bin/bootstrap
--- a/.bin/bootstrap
+++ b/.bin/bootstrap
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-function pre-link() {
+function bundle-core() {
 case "$OSTYPE" in
     darwin*)
         # https://brew.sh
@@ -26,7 +26,7 @@ case "$OSTYPE" in
 esac
 }
 
-function post-link() {
+function bundle-more() {
 case "$OSTYPE" in
     darwin*)
         # https://github.com/Homebrew/homebrew-bundle
@@ -39,13 +39,23 @@ esac
 
 # pre-conditions
 if ! [ -f xake ] ||  ! [ -x xake ]; then
-    echo "xake not found. abort."  >&2;
-    exit 1;
+    echo "xake not found. abort."  >&2
+    exit 1
 fi
 
-pre-link
+if ! (which python3.11 &> /dev/null); then
+    echo "pytho3.11 not found. abort." >&2
+    exit 1
+fi
 
-# default action: link
-./xake link
+# bootstrap
+set -x
 
-post-link
+export PIPENV_VENV_IN_PROJECT=true 
+
+bundle-core
+
+pipenv install
+pipenv run ./xake link
+
+bundle-more
